Add Magic Button
mgierlasinski/MagicGradients pull request #117
Opened 2020-09-16 12:34 UTC by bbenetskyy

2020-09-16 12:57 UTC, mgierlasinski requested changes

2020-09-16 12:57 UTC, mgierlasinski commented on MagicGradients/Controls/MagicButton.xaml
> +<ContentView
It could be just frame.

2020-09-16 12:57 UTC, mgierlasinski commented on MagicGradients/Controls/MagicButton.xaml.cs
> +        public static readonly BindableProperty TextProperty = BindableProperty.Create(
Please add properties above methods/contructor. And... please don't use regions, the year is not 2005 :)

2020-09-16 13:53 UTC, bbenetskyy commented on MagicGradients/Controls/MagicButton.xaml.cs
> +        public static readonly BindableProperty TextProperty = BindableProperty.Create(
but about `BindableProperty` before `ctor` I agree 😉

2020-09-22 07:14 UTC, mgierlasinski requested changes

2020-09-22 07:14 UTC, mgierlasinski commented on MagicGradients/Controls/MagicButton.xaml
> +                        Visual="Default" />
Default is Default :) No need to define in Xaml.

2020-09-22 07:14 UTC, mgierlasinski commented on MagicGradients/Controls/MagicButton.xaml
> +                        BackgroundColor="Transparent"
This removes Ripple effect, and button looses tap effect. Maybe simple Visual State Manager could handle that?

2020-09-22 07:14 UTC, mgierlasinski commented on MagicGradients/Controls/MagicButton.xaml
> +                    <magic:GradientView x:Name="GradientView" Margin="-2" />
Why do wee need this Margin?

2020-09-22 07:14 UTC, mgierlasinski commented on MagicGradients/Controls/MagicButton.xaml
> +    <!--<Frame
Please remove commented code.

2020-09-22 07:14 UTC, mgierlasinski commented on MagicGradients/Controls/MagicButton.xaml.cs
> +            //TopFrame.SetBinding(Frame.CornerRadiusProperty, new Binding(nameof(CornerRadius), source: this));
Please remove commented code.

2020-09-22 07:14 UTC, mgierlasinski commented on MagicGradients/Controls/MagicButton.xaml.cs
> +        public string Text
Please move properties above contructor.

2020-09-22 07:14 UTC, mgierlasinski commented on MagicGradients/Controls/MagicButton.xaml.cs
> +            defaultBindingMode: BindingMode.TwoWay);
Do we need two way binding? Also if default value is default for that type, no need to define it.

2020-09-22 07:16 UTC, bbenetskyy commented on MagicGradients/Controls/MagicButton.xaml
> +                        Visual="Default" />
this is true, just trash from another project

2020-09-22 10:09 UTC, bbenetskyy commented on MagicGradients/Controls/MagicButton.xaml
> +                    <magic:GradientView x:Name="GradientView" Margin="-2" />
it's not needed anymore

2020-09-22 10:18 UTC, bbenetskyy commented on MagicGradients/Controls/MagicButton.xaml
> +                        Visual="Default" />
If Project used a `Material Design` it's usually set in `ContentPage` for all content and for our button as well. In that case, it will have a visual bug at Android devices. We don't create a separate `Bindable Property` to handle it

2020-10-05 16:05 UTC, mgierlasinski commented on MagicGradients/Controls/MagicButton.xaml
> +                                        <Setter Property="Opacity" Value="1" />
Is it possible to override those states outside this control?
```
<MagicButton>
   <VisualStateManager.VisualStateGroups>
       <VisualStateGroup x:Name="CommonStates">
             <VisualState x:Name="Normal">...</VisualState >
       </VisualStateGroup>
   </VisualStateManager.VisualStateGroups>
</MagicButton>
```

2020-10-06 06:43 UTC, bbenetskyy commented on MagicGradients/Controls/MagicButton.xaml
> +                                        <Setter Property="Opacity" Value="1" />
I will check that, but Pressed or Disabled states may not be released because

Pressed - specific for a Xamarin Button

Disabled - we did not disable a whole control, only button layer, all other still accessible, but I will check it to be sure

2020-10-09 05:19 UTC, mgierlasinski approved these changes

2020-10-09 06:21 UTC, merged